[package]
name = "stow"
version = "0.1.0"
authors = ["wyp"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.20"
walkdir = "2"
same-file = "1"
ignore = "0"
regex = "1"
