[package]
name = "stow"
version = "0.1.0"
authors = ["wyp"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0"
same-file = "1"
regex = "1"
toml = "0"
serde = { version = "1", features = ["derive"] }

# ignore = "0"
# walkdir = "2"
