[package]
name = "stow"
version = "0.1.0"
authors = ["someone"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0"
same-file = "1"
toml = "0"
serde = { version = "1", features = ["derive"] }
shellexpand = "2"
tokio = { version = "1", features = ["full"] }
# ignore = "0"
# walkdir = "2"

[dependencies.regex]
version = "1"
default-features = false
features = ["std"]

[profile.release]
opt-level = 's'
lto = true
panic = 'abort'
